package dev.spyglass.android.settings

import androidx.compose.ui.graphics.Color
import dev.spyglass.android.core.ui.*

data class MinecraftUpdate(
    val version: String,
    val name: String,
    val releaseDate: String,
    val color: Color,
    val icon: SpyglassIcon,
    val changelog: List<String>,
)

object MinecraftUpdates {

    val JAVA_UPDATES = listOf(
        MinecraftUpdate(
            version = "1.0",
            name = "Adventure Update",
            releaseDate = "November 18, 2011",
            color = Emerald,
            icon = PixelIcons.Browse,
            changelog = listOf(
                "Official full release of Minecraft",
                "The End dimension and Ender Dragon boss fight",
                "Ender Pearls now teleport the player",
                "Enchanting system with enchantment table",
                "Brewing system with potions",
                "Nether Fortresses with Blaze spawners",
                "Villager NPCs in villages",
                "Animal breeding mechanics",
                "Hardcore mode",
                "Achievements system",
                "Hunger and food saturation system",
                "Snow Golems and Mooshrooms",
            ),
        ),
        MinecraftUpdate(
            version = "1.1",
            name = "January 2012 Update",
            releaseDate = "January 12, 2012",
            color = Emerald,
            icon = PixelIcons.Biome,
            changelog = listOf(
                "56 language translations",
                "Spawn eggs added to Creative mode",
                "Beaches and hills biome variants",
                "Golden Apples can be crafted with gold nuggets",
                "Bow enchantments (Power, Punch, Flame, Infinity)",
                "Superflat world type",
                "Ladders regain missing collision box",
            ),
        ),
        MinecraftUpdate(
            version = "1.2",
            name = "The Jungle Update",
            releaseDate = "March 1, 2012",
            color = Emerald,
            icon = PixelIcons.Biome,
            changelog = listOf(
                "Jungle biome with jungle trees",
                "Ocelots that can be tamed into cats",
                "Iron Golems defend villages",
                "Redstone Lamps",
                "Fire Charge throwable item",
                "New desert wells and desert villages",
                "Zombies can break wooden doors on Hard difficulty",
                "Zombie infection mechanic for villagers",
                "New world height: 0 to 256 (was 0 to 128)",
            ),
        ),
        MinecraftUpdate(
            version = "1.3",
            name = "The Adventure Update II",
            releaseDate = "August 1, 2012",
            color = Emerald,
            icon = PixelIcons.Structure,
            changelog = listOf(
                "Emeralds as a new currency",
                "Villager trading system",
                "Ender Chests with cross-dimensional storage",
                "Desert temples and jungle temples",
                "Tripwire Hooks and tripwire",
                "Written Books with Book and Quill",
                "Cocoa Beans grow on jungle wood",
                "Singleplayer now runs an internal server",
                "Bonus Chest and cheats world options",
                "Large Biomes world type",
            ),
        ),
        MinecraftUpdate(
            version = "1.4",
            name = "Pretty Scary Update",
            releaseDate = "October 25, 2012",
            color = NetherRed,
            icon = PixelIcons.Mob,
            changelog = listOf(
                "Wither boss and Wither Skeletons",
                "Beacon block with status effects",
                "Anvils for renaming and repairing",
                "Bats, Witches, and Zombie Villagers",
                "Command blocks for custom maps",
                "Carrots, Potatoes, and Pumpkin Pie",
                "Item Frames and Flower Pots",
                "Invisible and Night Vision potions",
                "Carrot on a Stick to control pigs",
                "Head/skull decorative blocks",
            ),
        ),
        MinecraftUpdate(
            version = "1.5",
            name = "Redstone Update",
            releaseDate = "March 13, 2013",
            color = Color(0xFFD32F2F),
            icon = PixelIcons.Blocks,
            changelog = listOf(
                "Redstone Block, Comparator, Daylight Sensor",
                "Hoppers for item transport",
                "Dropper and Trapped Chest",
                "Weighted Pressure Plates (light and heavy)",
                "Quartz blocks and Nether Quartz ore",
                "Activator Rails",
                "Improved minecart system",
                "TNT Minecarts and Hopper Minecarts",
                "Texture packs replaced by resource packs",
            ),
        ),
        MinecraftUpdate(
            version = "1.6",
            name = "Horse Update",
            releaseDate = "July 1, 2013",
            color = Color(0xFF8D6E63),
            icon = PixelIcons.Mob,
            changelog = listOf(
                "Horses, Donkeys, and Mules",
                "Horse Armor and leads (leashes)",
                "Hay Bales and Carpets",
                "Coal Block for compact fuel storage",
                "Hardened Clay and Stained Clay",
                "Name Tags for naming mobs",
                "New launcher with profile system",
                "Resource Pack system replaces texture packs",
                "Health Boost and Absorption status effects",
            ),
        ),
        MinecraftUpdate(
            version = "1.7",
            name = "The Update That Changed the World",
            releaseDate = "October 25, 2013",
            color = Emerald,
            icon = PixelIcons.Biome,
            changelog = listOf(
                "Massive world generation overhaul",
                "New biomes: Mesa, Mega Taiga, Roofed Forest, Birch Forest, Savanna, Extreme Hills+, Deep Ocean, Ice Plains Spikes",
                "Stained Glass and Stained Glass Panes",
                "New flowers: Sunflower, Lilac, Rose Bush, Peony, Blue Orchid, Allium, Azure Bluet, Tulips, Oxeye Daisy",
                "Packed Ice block",
                "Podzol and Red Sand",
                "New /summon and /achievement commands",
                "Fishing system overhaul with treasure and junk loot",
                "Amplified world type",
            ),
        ),
        MinecraftUpdate(
            version = "1.8",
            name = "Bountiful Update",
            releaseDate = "September 2, 2014",
            color = Color(0xFF78909C),
            icon = PixelIcons.Structure,
            changelog = listOf(
                "Ocean Monuments with Guardians and Elder Guardians",
                "Prismarine, Sea Lanterns, and Sponge blocks",
                "Rabbits and new rabbit-based items",
                "Armor Stands for displaying armor",
                "Banners with customizable patterns",
                "New stone types: Granite, Diorite, Andesite",
                "Slime Blocks with bouncing and sticky pistons",
                "New Spectator mode",
                "Multi-layer customized world type",
                "Endermites and new Enderman teleport behavior",
                "Depth Strider enchantment",
                "Door, fence, and fence gate variants for all wood types",
            ),
        ),
        MinecraftUpdate(
            version = "1.9",
            name = "Combat Update",
            releaseDate = "February 29, 2016",
            color = EnderPurple,
            icon = PixelIcons.Enchant,
            changelog = listOf(
                "Revamped combat with attack cooldown",
                "Dual-wielding with off-hand slot",
                "End Cities with Shulkers and Elytra",
                "End Ships, Purpur blocks, End Stone Bricks",
                "New arrow types: Spectral, Tipped",
                "Shields replace blocking with swords",
                "Igloos with secret basements",
                "Chorus Plants and Chorus Fruit",
                "Levitation and Luck status effects",
                "Dragon's Breath and Lingering Potions",
                "Ender Dragon can be re-summoned",
                "Beetroot crops",
                "Frost Walker and Mending enchantments",
            ),
        ),
        MinecraftUpdate(
            version = "1.10",
            name = "Frostburn Update",
            releaseDate = "June 8, 2016",
            color = NetherRed,
            icon = PixelIcons.Nether,
            changelog = listOf(
                "Polar Bears in ice biomes",
                "Husks in desert biomes",
                "Strays in cold biomes",
                "Magma Blocks in the Nether",
                "Nether Wart Blocks and Red Nether Bricks",
                "Bone Blocks from fossils",
                "Structure Blocks for map makers",
                "Auto-jump option added",
                "Fossils generate underground",
            ),
        ),
        MinecraftUpdate(
            version = "1.11",
            name = "Exploration Update",
            releaseDate = "November 14, 2016",
            color = Color(0xFF8D6E63),
            icon = PixelIcons.Structure,
            changelog = listOf(
                "Woodland Mansions with Illagers (Evokers, Vindicators, Vexes)",
                "Llamas with caravan behavior",
                "Shulker Boxes for portable storage",
                "Totem of Undying prevents death once",
                "Observer block detects state changes",
                "Exploration Maps from cartographers",
                "Cursed enchantments: Curse of Binding, Curse of Vanishing",
                "Iron and Gold Nuggets for smelting",
                "Rocket-powered Elytra flight",
            ),
        ),
        MinecraftUpdate(
            version = "1.12",
            name = "World of Color Update",
            releaseDate = "June 7, 2017",
            color = Color(0xFFFF7043),
            icon = PixelIcons.Blocks,
            changelog = listOf(
                "Concrete and Concrete Powder in 16 colors",
                "Glazed Terracotta in 16 vibrant patterns",
                "Parrots that mimic nearby mob sounds",
                "Advancements system replaces Achievements",
                "Crafting recipe book in the inventory",
                "New /function command system",
                "Narrator accessibility feature",
                "Illusioners (unused Illager variant)",
                "Knowledge Book item for unlocking recipes",
            ),
        ),
        MinecraftUpdate(
            version = "1.13",
            name = "Update Aquatic",
            releaseDate = "July 18, 2018",
            color = PotionBlue,
            icon = PixelIcons.Biome,
            changelog = listOf(
                "Complete ocean biome overhaul with warm, lukewarm, cold, and frozen variants",
                "Dolphins, Turtles, Tropical Fish, Cod, Salmon, Pufferfish, Drowned",
                "Coral Reefs with coral blocks and coral fans",
                "Shipwrecks with buried treasure maps",
                "Underwater Ruins (ocean ruins)",
                "Trident weapon with Riptide, Loyalty, Channeling, Impaling",
                "Conduits for underwater breathing",
                "Kelp, Seagrass, and Sea Pickles",
                "Phantom mob attacks sleep-deprived players",
                "The Flattening: block ID system overhaul",
                "Waterlogged blocks and swimming mechanic",
                "Heart of the Sea and Nautilus Shells",
                "Blue Ice block",
            ),
        ),
        MinecraftUpdate(
            version = "1.14",
            name = "Village & Pillage",
            releaseDate = "April 23, 2019",
            color = Color(0xFF8D6E63),
            icon = PixelIcons.Trade,
            changelog = listOf(
                "Complete village redesign with biome-specific architecture",
                "Pillager Outposts and Raids event",
                "Pillagers with Crossbows, Ravagers, and Raid Captain",
                "Villager profession overhaul with workstations",
                "Wandering Trader with random stock",
                "New blocks: Barrel, Blast Furnace, Smoker, Grindstone, Stonecutter, Bell, Lantern, Campfire, Cartography Table, Fletching Table, Smithing Table, Lectern, Loom, Composter, Sweet Berry Bush, Scaffolding, Bamboo",
                "Suspicious Stew with various effects",
                "Foxes in taiga biomes",
                "Cats as separate mob from Ocelots",
                "Leather Horse Armor dyeing",
                "New textures for nearly all blocks and items (JAPPA texture update)",
            ),
        ),
        MinecraftUpdate(
            version = "1.15",
            name = "Buzzy Bees",
            releaseDate = "December 10, 2019",
            color = Color(0xFFFFCA28),
            icon = PixelIcons.Mob,
            changelog = listOf(
                "Bees with pollination behavior",
                "Bee Nests in flower forests and plains",
                "Beehives craftable from planks and honeycomb",
                "Honey Bottles restore hunger, cure Poison",
                "Honeycomb and Honeycomb Blocks",
                "Honey Blocks with sticky and sliding mechanics",
                "Iron Golem cracking visual health indicator",
                "Major bug fix release (over 500 fixes)",
                "Performance improvements and rendering overhaul",
            ),
        ),
        MinecraftUpdate(
            version = "1.16",
            name = "Nether Update",
            releaseDate = "June 23, 2020",
            color = NetherRed,
            icon = PixelIcons.Nether,
            changelog = listOf(
                "Crimson Forest and Warped Forest biomes",
                "Soul Sand Valley and Basalt Deltas biomes",
                "Bastion Remnants with Piglin Brutes",
                "Ruined Portals scattered across both dimensions",
                "Piglins with bartering and gold armor respect",
                "Hoglins as Nether food source, Zoglins in Overworld",
                "Striders for lava riding",
                "Netherite: ancient debris, netherite ingots, and netherite tools/armor",
                "Respawn Anchors for Nether respawning",
                "Target Blocks and Lodestone",
                "Soul Fire, Soul Torches, Soul Lanterns",
                "Crying Obsidian, Blackstone, Basalt, Shroomlights, Nether Gold Ore",
                "Chains and new Nether vegetation",
            ),
        ),
        MinecraftUpdate(
            version = "1.17",
            name = "Caves & Cliffs: Part I",
            releaseDate = "June 8, 2021",
            color = EnderPurple,
            icon = PixelIcons.Blocks,
            changelog = listOf(
                "Amethyst Geodes with Budding Amethyst and Amethyst Clusters",
                "Spyglass for zooming in",
                "Copper ore and copper blocks with oxidation stages",
                "Lightning Rod attracts lightning",
                "Deepslate and Tuff stone types",
                "Axolotls in lush caves water",
                "Glow Squids with Glow Ink Sacs and Glow Item Frames",
                "Goats in mountain biomes with ramming behavior",
                "Dripstone Blocks and Pointed Dripstone",
                "Moss Blocks, Azalea, and Dripleaf plants",
                "Glow Berries and Glow Lichen",
                "Candles in 16 colors",
                "Raw ore items (Raw Iron, Raw Gold, Raw Copper)",
                "Powder Snow with freezing mechanic",
                "Tinted Glass blocks light but is transparent",
            ),
        ),
        MinecraftUpdate(
            version = "1.18",
            name = "Caves & Cliffs: Part II",
            releaseDate = "November 30, 2021",
            color = Color(0xFF78909C),
            icon = PixelIcons.Biome,
            changelog = listOf(
                "World height expanded: Y -64 to Y 320",
                "Massive cave generation overhaul",
                "Cheese caves, spaghetti caves, and noodle caves",
                "Lush Caves biome underground",
                "Dripstone Caves biome underground",
                "Noise caves with aquifers create underground lakes",
                "New mountain terrain: Meadow, Grove, Snowy Slopes, Jagged Peaks, Frozen Peaks, Stony Peaks",
                "Ore distribution overhaul with new generation patterns",
                "Deepslate ore variants for all ores",
                "Music by Lena Raine and Kumi Tanioka",
            ),
        ),
        MinecraftUpdate(
            version = "1.19",
            name = "The Wild Update",
            releaseDate = "June 7, 2022",
            color = Color(0xFF004D40),
            icon = PixelIcons.Biome,
            changelog = listOf(
                "Deep Dark biome deep underground",
                "Ancient Cities in the Deep Dark",
                "Warden: blind, powerful mob that detects vibrations",
                "Sculk blocks: Sculk, Sculk Vein, Sculk Catalyst, Sculk Sensor, Sculk Shrieker",
                "Mangrove Swamp biome with mangrove trees",
                "Mangrove wood set and Mud Bricks",
                "Frogs with warm, temperate, and cold variants",
                "Tadpoles that grow into frogs",
                "Froglight blocks in 3 colors",
                "Allays collect and deliver items",
                "Recovery Compass points to last death location",
                "Swift Sneak enchantment for crouching speed",
                "Darkness status effect from Sculk Shriekers",
                "Chest Boats for item transport",
            ),
        ),
        MinecraftUpdate(
            version = "1.20",
            name = "Trails & Tales",
            releaseDate = "June 7, 2023",
            color = Color(0xFFFF7043),
            icon = PixelIcons.Structure,
            changelog = listOf(
                "Archaeology: Suspicious Sand, Suspicious Gravel, and Brush tool",
                "Pottery Sherds and Decorated Pots",
                "Trail Ruins structure with unique sherds",
                "Cherry Grove biome with Cherry Blossom trees",
                "Cherry wood set (pink-themed)",
                "Bamboo wood set and Bamboo Raft",
                "Armor Trims with 16 patterns and 10 materials",
                "Smithing Template system for armor trimming and netherite",
                "Sniffer mob hatched from Sniffer Eggs",
                "Torchflower and Pitcher Plant from Sniffer",
                "Camels: two-player rideable mount",
                "Hanging Signs with customizable text",
                "Chiseled Bookshelves for storing books",
                "Calibrated Sculk Sensor with Comparator",
            ),
        ),
        MinecraftUpdate(
            version = "1.21",
            name = "Tricky Trials",
            releaseDate = "June 13, 2024",
            color = Color(0xFFFF6F00),
            icon = PixelIcons.Structure,
            changelog = listOf(
                "Trial Chambers: massive underground structure",
                "Trial Spawners that scale to player count",
                "Breeze mob with wind charge attacks",
                "Wind Charge throwable item for players",
                "Vault blocks with loot rewards",
                "Ominous Trials with Ominous Vault rewards",
                "Heavy Core item and Mace weapon",
                "Mace enchantments: Density, Breach, Wind Burst",
                "Copper Bulb redstone light block",
                "Copper Doors, Trapdoors, and Grates",
                "Crafter block for automated crafting",
                "Trial Explorer Map from cartographers",
                "New banner patterns and pottery sherds",
                "New music discs: Creator and Precipice",
                "Paintings by artist Sarah Boeving",
                "Bolt and Flow Armor Trim patterns",
            ),
        ),
    )

    /** Returns the update info for a given version string, falling back to the major version. */
    fun forVersion(version: String): MinecraftUpdate? =
        JAVA_UPDATES.find { it.version == version }
            ?: JAVA_UPDATES.find { version.startsWith(it.version + ".") }

    /** Returns the latest update. */
    fun latest(): MinecraftUpdate = JAVA_UPDATES.last()
}
