import java.util.Calendar
import java.util.Properties
import java.util.TimeZone

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    // Firebase plugins — only applied when google-services.json exists
    alias(libs.plugins.google.services) apply false
    alias(libs.plugins.firebase.crashlytics) apply false
    alias(libs.plugins.firebase.perf) apply false
    alias(libs.plugins.baselineprofile)
    alias(libs.plugins.detekt)
}

// Conditionally apply Firebase plugins when google-services.json exists
if (file("google-services.json").exists()) {
    apply(plugin = libs.plugins.google.services.get().pluginId)
    apply(plugin = libs.plugins.firebase.crashlytics.get().pluginId)
    apply(plugin = libs.plugins.firebase.perf.get().pluginId)
}

// CalVer: versionCode = YYMMDDHHmm (fits Int), versionName = "YYYY.MMDD.HHmm-alpha"
// Must use America/Chicago to match the release tag generated by CI (TZ='America/Chicago')
val calVerDate: Calendar = Calendar.getInstance(TimeZone.getTimeZone("America/Chicago"))
val calVerCode = (calVerDate.get(Calendar.YEAR) - 2000) * 10_000_000 +
    (calVerDate.get(Calendar.MONTH) + 1) * 1_000_000 +
    calVerDate.get(Calendar.DAY_OF_MONTH) * 10_000 +
    calVerDate.get(Calendar.HOUR_OF_DAY) * 100 +
    calVerDate.get(Calendar.MINUTE)
val calVerName = "%d.%02d%02d.%02d%02d-alpha".format(
    calVerDate.get(Calendar.YEAR),
    calVerDate.get(Calendar.MONTH) + 1,
    calVerDate.get(Calendar.DAY_OF_MONTH),
    calVerDate.get(Calendar.HOUR_OF_DAY),
    calVerDate.get(Calendar.MINUTE),
)

val localProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}

android {
    namespace = "dev.spyglass.android"
    compileSdk = 35

    signingConfigs {
        create("release") {
            val ks = localProps.getProperty("RELEASE_STORE_FILE")
            if (ks != null) {
                storeFile = file(ks)
                storePassword = localProps.getProperty("RELEASE_STORE_PASSWORD", "")
                keyAlias = localProps.getProperty("RELEASE_KEY_ALIAS", "")
                keyPassword = localProps.getProperty("RELEASE_KEY_PASSWORD", "")
            }
        }
    }

    defaultConfig {
        applicationId = "dev.spyglass.android"
        minSdk = 26
        targetSdk = 35
        versionCode = calVerCode
        versionName = calVerName

        // AdMob — defaults to test IDs; override in local.properties for production
        val testAppId = "ca-app-pub-3940256099942544~3347511713"
        val testBannerId = "ca-app-pub-3940256099942544/9214589741"
        val admobAppId = localProps.getProperty("ADMOB_APP_ID")
            .let { if (it.isNullOrBlank()) testAppId else it }
        val admobBannerId = localProps.getProperty("ADMOB_BANNER_ID")
            .let { if (it.isNullOrBlank()) testBannerId else it }
        manifestPlaceholders["admobAppId"] = admobAppId
        buildConfigField("String", "ADMOB_BANNER_ID", "\"$admobBannerId\"")
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.findByName("release")
        }
        create("benchmark") {
            initWith(buildTypes.getByName("release"))
            matchingFallbacks += listOf("release")
            isDebuggable = false
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions { jvmTarget = "17" }

    ksp {
        arg("room.schemaLocation", "$projectDir/schemas")
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }
}

baselineProfile {
    automaticGenerationDuringBuild = false
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.activity.compose)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.runtime.compose)
    implementation(libs.lifecycle.viewmodel.compose)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.foundation)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons)
    debugImplementation(libs.compose.ui.tooling)

    implementation(libs.navigation.compose)

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    implementation(libs.datastore.preferences)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)
    // Debug tools
    implementation(libs.timber)
    debugImplementation(libs.leakcanary)

    // OkHttp
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging)

    // Firebase — disabled at runtime by default; enabled only with user consent
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.crashlytics)
    implementation(libs.firebase.analytics)
    implementation(libs.firebase.perf)

    // In-App Review
    implementation(libs.play.review.ktx)

    // Ads — AdMob + mediation adapters
    implementation(libs.play.services.ads)
    implementation(libs.admob.mediation.meta)
    implementation(libs.admob.mediation.unity)
    implementation(libs.admob.mediation.applovin)
    implementation(libs.admob.mediation.ironsource)
    implementation(libs.unity.ads)

    // Window Manager
    implementation(libs.window)

    // WorkManager & Paging
    implementation(libs.work.runtime.ktx)
    implementation(libs.paging.runtime.ktx)
    implementation(libs.paging.compose)

    // Spyglass Connect — QR scanning + CameraX
    implementation(libs.zxing.android.embedded)
    implementation(libs.camerax.core)
    implementation(libs.camerax.camera2)
    implementation(libs.camerax.lifecycle)
    implementation(libs.camerax.view)

    // Baseline Profiles
    implementation(libs.profileinstaller)

    // Testing
    testImplementation(libs.junit)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.kotlin)
    testImplementation(libs.coroutines.test)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    androidTestImplementation(libs.room.testing)
    androidTestImplementation(libs.compose.ui.test.junit4)
    debugImplementation(libs.compose.ui.test.manifest)
}
