package dev.spyglass.android.core.ui

/**
 * Texture lookup for all Minecraft mob entities.
 * Icons sourced from Entity-Icons (CC0 1.0).
 */
object MobTextures {
    private val textureMap = mapOf(
        "allay" to "mob_allay",
        "armadillo" to "mob_armadillo",
        "axolotl" to "mob_axolotl",
        "bat" to "mob_bat",
        "bee" to "mob_bee",
        "blaze" to "mob_blaze",
        "bogged" to "mob_bogged",
        "breeze" to "mob_breeze",
        "camel" to "mob_camel",
        "cat" to "mob_cat",
        "cave_spider" to "mob_cave_spider",
        "chicken" to "mob_chicken",
        "chicken_jockey" to "mob_chicken_jockey",
        "cod" to "mob_cod",
        "cow" to "mob_cow",
        "creaking" to "mob_creaking",
        "creeper" to "mob_creeper",
        "dolphin" to "mob_dolphin",
        "donkey" to "mob_donkey",
        "drowned" to "mob_drowned",
        "elder_guardian" to "mob_elder_guardian",
        "ender_dragon" to "mob_ender_dragon",
        "enderman" to "mob_enderman",
        "endermite" to "mob_endermite",
        "evoker" to "mob_evoker",
        "fox" to "mob_fox",
        "frog" to "mob_frog",
        "ghast" to "mob_ghast",
        "glow_squid" to "mob_glow_squid",
        "goat" to "mob_goat",
        "guardian" to "mob_guardian",
        "hoglin" to "mob_hoglin",
        "horse" to "mob_horse",
        "husk" to "mob_husk",
        "iron_golem" to "mob_iron_golem",
        "llama" to "mob_llama",
        "trader_llama" to "mob_llama",
        "magma_cube" to "mob_magma_cube",
        "mooshroom" to "mob_mooshroom",
        "mule" to "mob_mule",
        "ocelot" to "mob_ocelot",
        "panda" to "mob_panda",
        "parrot" to "mob_parrot",
        "phantom" to "mob_phantom",
        "pig" to "mob_pig",
        "piglin" to "mob_piglin",
        "piglin_brute" to "mob_piglin_brute",
        "pillager" to "mob_pillager",
        "polar_bear" to "mob_polar_bear",
        "pufferfish" to "mob_pufferfish",
        "rabbit" to "mob_rabbit",
        "ravager" to "mob_ravager",
        "salmon" to "mob_salmon",
        "sheep" to "mob_sheep",
        "shulker" to "mob_shulker",
        "silverfish" to "mob_silverfish",
        "skeleton" to "mob_skeleton",
        "skeleton_horse" to "mob_skeleton_horse",
        "slime" to "mob_slime",
        "sniffer" to "mob_sniffer",
        "snow_golem" to "mob_snow_golem",
        "spider" to "mob_spider",
        "spider_jockey" to "mob_spider_jockey",
        "squid" to "mob_squid",
        "stray" to "mob_stray",
        "strider" to "mob_strider",
        "tadpole" to "mob_tadpole",
        "tropical_fish" to "mob_tropical_fish",
        "turtle" to "mob_turtle",
        "vex" to "mob_vex",
        "villager" to "mob_villager",
        "vindicator" to "mob_vindicator",
        "wandering_trader" to "mob_wandering_trader",
        "warden" to "mob_warden",
        "witch" to "mob_witch",
        "wither" to "mob_wither",
        "wither_skeleton" to "mob_wither_skeleton",
        "zombie_horse" to "mob_wither_skeleton_horse",
        "wolf" to "mob_wolf",
        "zombie" to "mob_zombie",
        "zombie_villager" to "mob_zombie_villager",
        "zombified_piglin" to "mob_zombie_pigman",
        "zoglin" to "mob_zoglin",
    )

    fun get(mobId: String): SpyglassIcon? {
        val filename = textureMap[mobId] ?: return null
        return TextureManager.resolveOrBundled(filename)
    }
}
