package dev.spyglass.android.core.ui

import dev.spyglass.android.R

object PixelIcons {
    val Blocks    = SpyglassIcon.Drawable(R.drawable.ic_pixel_blocks)
    val Crafting  = SpyglassIcon.Drawable(R.drawable.ic_pixel_crafting)
    val Mob       = SpyglassIcon.Drawable(R.drawable.ic_pixel_mob)
    val Allay     = SpyglassIcon.Drawable(R.drawable.ic_pixel_allay)
    val Biome     = SpyglassIcon.Drawable(R.drawable.ic_pixel_biome)
    val Enchant   = SpyglassIcon.Drawable(R.drawable.ic_pixel_enchant)
    val Potion    = SpyglassIcon.Drawable(R.drawable.ic_pixel_potion)
    val Trade     = SpyglassIcon.Drawable(R.drawable.ic_pixel_trade)
    val Structure = SpyglassIcon.Drawable(R.drawable.ic_pixel_structure)
    val Item      = SpyglassIcon.Drawable(R.drawable.ic_pixel_items)
    val Fill      = SpyglassIcon.Drawable(R.drawable.ic_pixel_fill)
    val Smelt     = SpyglassIcon.Drawable(R.drawable.ic_pixel_smelt)
    val Storage   = SpyglassIcon.Drawable(R.drawable.ic_pixel_storage)
    val Nether    = SpyglassIcon.Drawable(R.drawable.ic_pixel_nether)
    val Shapes    = SpyglassIcon.Drawable(R.drawable.ic_pixel_shapes)
    val Anvil     = SpyglassIcon.Drawable(R.drawable.ic_pixel_anvil)
    val Calculator = SpyglassIcon.Drawable(R.drawable.ic_pixel_calculator)
    val Browse    = SpyglassIcon.Drawable(R.drawable.ic_pixel_browse)
    val Search    = SpyglassIcon.Drawable(R.drawable.ic_pixel_search)
    val SearchOff = SpyglassIcon.Drawable(R.drawable.ic_pixel_search_off)
    val Bookmark  = SpyglassIcon.Drawable(R.drawable.ic_pixel_bookmark)
    val Menu      = SpyglassIcon.Drawable(R.drawable.ic_pixel_menu)
    val Todo      = SpyglassIcon.Drawable(R.drawable.ic_pixel_todo)
    val Maze      = SpyglassIcon.Drawable(R.drawable.ic_pixel_maze)
    val Clock     = SpyglassIcon.Drawable(R.drawable.ic_pixel_clock)
    val Advancement = SpyglassIcon.Drawable(R.drawable.ic_pixel_advancement)
    val Command   = SpyglassIcon.Drawable(R.drawable.ic_pixel_command)
    val Waypoints = SpyglassIcon.Drawable(R.drawable.ic_pixel_waypoints)
    val Torch     = SpyglassIcon.Drawable(R.drawable.ic_pixel_torch)
    val Globe     = SpyglassIcon.Drawable(R.drawable.ic_pixel_globe)
}
